project:
  name: Secrover
domains:
  - secrover.org
  - secrover.com
repos:
  - url: git@github.com:Secrover/secrover.org.git
    branch: master
    description: Main project
  - url: git@github.com:Secrover/Secrover.git
    branch: master
    description: Website