project:
  name: Secrover
domains:
  - secrover.org
  - secrover.com
repos:
  - url: https://github.com/Secrover/secrover.org.git
    branch: master
    description: Main project
  - url: https://github.com/Secrover/Secrover.git
    branch: master
    description: Website